### ISSUE TITLE
Figure out latest deploy to Bluemix methodology

### ISSUE THREAD

**Issue by rajrsingh** [codait-advocates/weather-api-nodejs#3]

**Comment by rajrsingh** [comment]
use `ibmcloud` CLI? Is `bx cf ...` dead? Manifest.yml same as always?

**Comment by vabarbosa** [comment]
we should be using `ibmcloud` CLI moving forward.
from https://console.bluemix.net/docs/cli/reference/bluemix_cli/bx_cli.html#bluemix_cli

> As of May 2018 the IBM Cloud CLI commands have changed from `bluemix` and `bx` to `ibmcloud`. However you can still use the `bluemix` and `bx` CLI commands until they are removed at a later date.

no date yet as to when support for `bluemix` and `bx` CLI will be removed.

**Comment by rajrsingh** [comment]
@vabarbosa do you know if we can still do a "deploy to bluemix" button in a GH repo?

**Comment by vabarbosa** [comment]
yes, still can:
https://console.bluemix.net/docs/services/ContinuousDelivery/deploy_button.html#deploy-button

**Comment by rajrsingh** [comment]
with this manifest file:

```
---
applications:
- name: weather-api-nodejs
  command: npm start
  path: .
  memory: 256M
  instances: 1
  env:
    WEATHER_API_KEY: yourkeygoeshere
    NPM_CONFIG_PRODUCTION: false
  buildpack: sdk-for-nodejs
  no-route: true
```

the deploy to ibm cloud button works
